global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'app-container:8080' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus-container:9090' ]